### ISSUE TITLE
  About the problem of camera sensor

### ISSUE THREAD

**Issue by YWPLJQ** [MaisJamal/carla_apollo_bridge#1]
Hello, I have a question to ask you.
When running your program, add the following lines of code:
['sensor.camera.instance_segmentation', cc.CityScapesPalette, 'Camera Instance Segmentation (CityScapes Palette)', {}],
['sensor.camera.instance_segmentation', cc.Raw, 'Camera Instance Segmentation (Raw)', {}],
['sensor.camera.optical_flow', cc.Raw, 'Optical Flow', {}],
An error occurs, causing the camera addition to fail.
What is the reason for this? How can you add your contact details to the following if it is convenient?

**Comment by MaisJamal** [comment]
Hello, currently the bridge doesn't support publishing camera images to Apollo, but as a temporally alternative, I added to the bridge the possibility of publishing ground truth about all obstacles in Carla scene. You just have to set the parameter publish_obstacles_ground_truth to "true" in carla_apollo_bridge/config/bridge_settings.yaml .
