### ISSUE TITLE
docker image can not build

### ISSUE THREAD

**Issue by tk-menot** [MaisJamal/carla_apollo_bridge#16]
Thank you very much for your work, it is perfect and solves many of my problems. But when I build the docker image, I find that auroai/cyber cannot be pulled. Do you have the downloaded image file? Can you share it through Google Drive or other methods? Thank you again for your perfect work

**Comment by MaisJamal** [comment]
Here is the docker image [auroai/cyber](https://drive.google.com/file/d/1keoBH1d4RO3AzQ2KugujBTNovrdZ9Rx9/view?usp=sharing) 
you can download it and add it by
`docker load -i <path to image file>`

**Comment by tk-menot** [comment]
thank you for your reply!
