### ISSUE TITLE
why is there  a shift * math.cos(heading) in the localization?

### ISSUE THREAD

**Issue by ThisisKKya** [MaisJamal/carla_apollo_bridge#2]
Hello! Thank you for your great work about the carla bridge. The project is awsome, but I have some questions about the code.
`child.transform.translation.x = x - shift * math.cos(heading)`
`child.transform.translation.y = y - shift * math.sin(heading)`
Why we need to do this before sending to apollo? And how do you calculate the shift which is 1.355? Is this the key to make the bridge work properly?

**Comment by MaisJamal** [comment]
Hello,
This shift is necessary to map the difference in the origin of two coordination systems. In Apollo, the origin of the vehicle's coordination system is in the middle of the wheels rear axis , while in Carla the origin of the vehicle's coordination system is in the middle of the vehicle. So to find the real location in Apollo map, you should always shift the origin.
I defined the sift value as 1.355 m after I have calculated the distance between rear axis and the center of the vehicle depending on "vehicle parameters" in Apollo.
