### ISSUE TITLE
Multiple apollo configuration on the same machine

### ISSUE THREAD

**Issue by gmvc2000** [MaisJamal/carla_apollo_bridge#4]
I want to connect multiple apollo to the carla simulator. However each apollo stack needs to be in separate containers for isolation. They also need to be in separate networks so as to not share modules in dreamview. Is it possible in this configuration of the bridge and Carla?

**Comment by MaisJamal** [comment]
In the current configuration of the bridge you can't connect multiple Apollo instances and Carla. In the bridge I assume that in Carla there is only one "hero" agent and it's of the type Lincoln. 
However, I think you can run multiple instances of the bridge and connect each to one Apollo by a specific IP, taking into consideration that there will be multiple heroes in Carla, and you should differentiate between them in each bridge.
