### ISSUE TITLE
can apollo7.0 be substitute by apollo5.0？

### ISSUE THREAD

**Issue by 2019211753** [MaisJamal/carla_apollo_bridge#5]
i want to use apollo5.0 in my project，thanks!

**Comment by MaisJamal** [comment]
Yes you can follow the same instructions for Apollo5.0 . It should work fine, just have to change the class Type in carla_apollo_bridge/carla_cyber_bridge/msg_getters.py  , because obstacle type in proto in apollo v7.0.0 has modifications of the one in apollo v5.0.0

**Comment by 2019211753** [comment]
> Yes you can follow the same instructions for Apollo5.0 . It should work fine, just have to change the class Type in carla_apollo_bridge/carla_cyber_bridge/msg_getters.py , because obstacle type in proto in apollo v7.0.0 has modifications of the one in apollo v5.0.0

Thanks for getting back to me!
I have a question: Apart from modifying the msg_getters.py file, is it sufficient to clone Apollo and checkout to version r5.0?
And another question is, what is the obstacle type in the proto in Apollo 5.0? What are the differences between versions 5.0 and 7.0?
I'm not quite familiar with that. Thank you once again for your guidance!
