### ISSUE TITLE
The dreamview is keep flashing and i can't control the car by Routing Editing

### ISSUE THREAD

**Issue by 2019211753** [MaisJamal/carla_apollo_bridge#8]
I grab a video to describe my problem. I think i follow the instructions step by step. My device is 3080. Is it because my graphics card isn't powerful enough?

The modules are as follows.
![image](https://github.com/MaisJamal/carla_apollo_bridge/assets/65377379/59baede2-5805-4b18-aa63-44dc76950614)

**Comment by 2019211753** [comment]
Here is the video:
https://github.com/MaisJamal/carla_apollo_bridge/assets/65377379/371e74d3-641d-4087-84c3-5730b8bac9a4

**Comment by PhilWallace** [comment]
![Screenshot from 2023-08-05 02-26-27](https://github.com/MaisJamal/carla_apollo_bridge/assets/37956889/851b1549-1efd-4b08-bf72-ce3d7d5fb948)

I met the similar problem:

1. Dreamview keeps flashing.
2. However, the position of the manual_control vehicle seems to be consistent with the position in Dreamview. But the heading angle of two vehicles are different.
3. Dreamview can perceive the brake and throttle command from manual_control vehicle, indicating the bridge is somehow working.

I guess there are still some buggy parts in the bridge code.

**Comment by MaisJamal** [comment]
@PhilWallace Hello,
There should not be a wrong heading angle, please follow the installation's instructions carefully. 
I will record a detailed video tutorial soon, so it will be clearer to everyone.

**Comment by 2019211753** [comment]
@MaisJamal 
Looking forward to your video tutorial! We very need it.

**Comment by MaisJamal** [comment]
@2019211753 please check and pull the latest version of the bridge and run manual_control.py instead of manual_control_13.py
In another [opened issue](https://github.com/MaisJamal/carla_apollo_bridge/issues/12#issue-1913511280) , they say they have faced a similar problem of flashing dreamview by running manual_control_13.py script and now it is working fine by the script manual_contorl.py.

**Comment by MaisJamal** [comment]
@PhilWallace Can you please elaborate on the issue of different heading angle of two vehicles in Carla and in Apollo.
It seems like other users of the bridge are not facing this issue.

**Comment by PhilWallace** [comment]
> @PhilWallace Can you please elaborate on the issue of different heading angle of two vehicles in Carla and in Apollo. It seems like other users of the bridge are not facing this issue.

I'm recently not running the project. I will detail this problem If I meet it again. Thanks

**Comment by MaisJamal** [comment]
End-to-end video tutorial, how to install, configure and use this Carla-Apollo-Bridge, with Carla simulator (v0.9.13) and Apollo driving software (v8.0.0):
https://youtu.be/2dQC3ToJGJU?si=6mZMHP1RRZHPRggX

**Comment by 2019211753** [comment]
> End-to-end video tutorial, how to install, configure and use this Carla-Apollo-Bridge, with Carla simulator (v0.9.13) and Apollo driving software (v8.0.0): https://youtu.be/2dQC3ToJGJU?si=6mZMHP1RRZHPRggX

Thanks for your contribution!
